version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project

  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project

jobs:
  build-frontend:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Clone Front_VaccinationApp
          command: |
            git clone --branch "$FRONT_BRANCH" https://$CIRCLE_GH_TOKEN@${FRONT_REPO_URL#https://} frontend

      - run:
          name: Install Dependencies
          command: |
            cd frontend
            npm install --legacy-peer-deps

      - run:
          name: Build Angular App
          command: |
            cd frontend
            npm run build --configuration=production

      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Install AWS CLI
          command: |
            sudo apt update && sudo apt install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Authenticate to AWS ECR
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
            aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$FRONT_ECR_REPO"

      - run:
          name: Build and Push Docker Image (Frontend)
          command: |
            cd frontend
            BUILD_TAG="$FRONT_ECR_REPO:${CIRCLE_BUILD_NUM}"
            docker build -t "$BUILD_TAG" .
            docker push "$BUILD_TAG"
            docker tag "$BUILD_TAG" "$FRONT_ECR_REPO:latest"
            docker push "$FRONT_ECR_REPO:latest"

      - run:
          name: Update Helm Repo values.yaml (Frontend)
          command: |
            git config --global user.name "CircleCI_Pipeline"
            git config --global user.email "circleci@firasbennacib.com"
            git clone --branch "$HELM_REPO_BRANCH" https://$CIRCLE_GH_TOKEN@${HELM_REPO_URL#https://} kube-proj
            cd kube-proj
            sed -i "s|\(repository:.*frontend.*\)\n.*tag:.*|\\1\n    tag: \"${CIRCLE_BUILD_NUM}\"|" values.yaml
            git add values.yaml
            git commit -m "ci: update frontend image tag to ${CIRCLE_BUILD_NUM}" || echo "No changes to commit"
            git push origin "$HELM_REPO_BRANCH"

  build-backend:
    executor: java-executor
    steps:
      - checkout

      - run:
          name: Clone Back_vaccinationApp
          command: |
            git clone --branch "$BACK_BRANCH" https://$CIRCLE_GH_TOKEN@${BACK_REPO_URL#https://} backend

      - run:
          name: Build Spring Boot App
          command: |
            cd backend
            mvn clean install -DskipTests

      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Install AWS CLI
          command: |
            sudo apt update && sudo apt install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Authenticate to AWS ECR
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
            aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$BACK_ECR_REPO"

      - run:
          name: Build and Push Docker Image (Backend)
          command: |
            cd backend
            BUILD_TAG="$BACK_ECR_REPO:${CIRCLE_BUILD_NUM}"
            docker build -f Dockerfile.circleci -t "$BUILD_TAG" .
            docker push "$BUILD_TAG"
            docker tag "$BUILD_TAG" "$BACK_ECR_REPO:latest"
            docker push "$BACK_ECR_REPO:latest"

      - run:
          name: Update Helm Repo values.yaml (Backend)
          command: |
            git config --global user.name "CircleCI_Pipeline"
            git config --global user.email "circleci@firasbennacib.com"
            git clone --branch "$HELM_REPO_BRANCH" https://$CIRCLE_GH_TOKEN@${HELM_REPO_URL#https://} kube-proj
            cd kube-proj
            sed -i "s|\(repository:.*backend.*\)\n.*tag:.*|\\1\n    tag: \"${CIRCLE_BUILD_NUM}\"|" values.yaml
            git add values.yaml
            git commit -m "ci: update backend image tag to ${CIRCLE_BUILD_NUM}" || echo "No changes to commit"
            git push origin "$HELM_REPO_BRANCH"

workflows:
  version: 2
  build-all:
    jobs:
      - build-frontend
      - build-backend
